// Generates src/environments/environment.ts and environment.development.ts from
// process.env (loaded from .env if present). Runs automatically before start/build/test
// via the pre* npm script hooks — see package.json. Never commit the generated files;
// only .env.example (placeholders) is tracked in git.
import { writeFileSync } from 'node:fs';

try {
  process.loadEnvFile('.env');
} catch {
  // No .env file (e.g. CI provides real env vars directly) — fall back to placeholders below.
}

function env(name, fallback) {
  return process.env[name] ?? fallback;
}

const values = {
  tenantId: env('TENANT_ID', 'YOUR_TENANT_ID'),
  apiClientId: env('API_CLIENT_ID', 'YOUR_API_APP_CLIENT_ID'),
  spaClientId: env('SPA_CLIENT_ID', 'YOUR_SPA_APP_CLIENT_ID'),
  apiBaseUrl: env('API_BASE_URL', 'http://localhost:8080/api'),
};

function render(production) {
  return `// Auto-generated by scripts/generate-env.mjs from .env — do not edit by hand or commit.
import { Environment } from './environment.model';

export const environment: Environment = {
  production: ${production},
  tenantId: '${values.tenantId}',
  apiClientId: '${values.apiClientId}',
  spaClientId: '${values.spaClientId}',
  apiBaseUrl: '${values.apiBaseUrl}',
};
`;
}

writeFileSync('src/environments/environment.ts', render(true));
writeFileSync('src/environments/environment.development.ts', render(false));

console.log('Generated src/environments/environment*.ts');
